using CodeDesignPlus.Net.Microservice.FileStorage.Application.FileStorage.DataTransferObjects;

namespace CodeDesignPlus.Net.Microservice.FileStorage.Rest.Controllers;

/// <summary>
/// Manages file storage operations: listing, retrieval, upload, and download.
/// </summary>
/// <remarks>
/// All endpoints are protected by the global authorization policy defined in <c>Program.cs</c>
/// (<c>MapControllers().RequireAuthorization()</c>). A valid JWT bearer token is required on every request.
///
/// The cloud storage backend (Azure Blob, Azure File, or Local) is resolved at runtime from the
/// <c>FileStorage</c> section of <c>appsettings.json</c> and is completely opaque to callers.
/// Consumer services should persist only the <see cref="Guid"/> identifier returned by
/// <see cref="Upload"/>, never a cloud URL.
/// </remarks>
[Route("api/[controller]")]
[ApiController]
[Produces("application/json")]
public class FileStorageController(IMediator mediator) : ControllerBase
{
    /// <summary>
    /// Returns a paginated, filtered, and sorted list of file-storage records.
    /// </summary>
    /// <param name="criteria">
    /// OData-style query parameters (<c>filter</c>, <c>orderby</c>, <c>top</c>, <c>skip</c>)
    /// forwarded directly to the Mongo repository via <see cref="GetAllFileStorageQuery"/>.
    /// </param>
    /// <param name="cancellationToken">Propagates cancellation from the HTTP pipeline.</param>
    /// <returns>A collection of <see cref="FileStorageDto"/> matching the supplied criteria.</returns>
    /// <response code="200">Query executed successfully; body contains the result set (may be empty).</response>
    /// <response code="401">Missing or invalid bearer token.</response>
    [HttpGet]
    [ProducesResponseType(typeof(IEnumerable<FileStorageDto>), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> GetFiles([FromQuery] C.Criteria criteria, CancellationToken cancellationToken)
    {
        var result = await mediator.Send(new GetAllFileStorageQuery(criteria), cancellationToken);

        return Ok(result);
    }

    /// <summary>
    /// Returns a single file-storage record by its unique identifier.
    /// </summary>
    /// <param name="id">The <see cref="Guid"/> of the <c>FileStorageAggregate</c> to retrieve.</param>
    /// <param name="cancellationToken">Propagates cancellation from the HTTP pipeline.</param>
    /// <returns>The <see cref="FileStorageDto"/> for the requested aggregate.</returns>
    /// <response code="200">Record found; body contains the <see cref="FileStorageDto"/>.</response>
    /// <response code="401">Missing or invalid bearer token.</response>
    /// <response code="404">No aggregate exists for the supplied <paramref name="id"/>.</response>
    [HttpGet("{id}")]
    [ProducesResponseType(typeof(FileStorageDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> GetFileById(Guid id, CancellationToken cancellationToken)
    {
        var query = new GetFileStorageByIdQuery(id);

        var result = await mediator.Send(query, cancellationToken);

        return Ok(result);
    }

    /// <summary>
    /// Returns a time-limited signed URL that grants temporary direct access to the specified file.
    /// </summary>
    /// <remarks>
    /// The signed URL is generated by the underlying cloud provider (<c>IFileStorage</c>) and is
    /// valid for a short period (configured per provider). Callers should not cache or share the URL
    /// beyond its intended use; request a new one when the previous one expires.
    /// </remarks>
    /// <param name="id">The <see cref="Guid"/> of the <c>FileStorageAggregate</c> that owns the file.</param>
    /// <param name="cancellationToken">Propagates cancellation from the HTTP pipeline.</param>
    /// <returns>An object containing the signed URL and its expiration metadata.</returns>
    /// <response code="200">Signed URL generated successfully.</response>
    /// <response code="401">Missing or invalid bearer token.</response>
    /// <response code="404">No aggregate exists for the supplied <paramref name="id"/>.</response>
    [HttpGet("signed-url/{id}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> GetSignedUrlAsync(Guid id, CancellationToken cancellationToken)
    {
        var query = new GetFileStorageByIdQuery(id);

        var result = await mediator.Send(query, cancellationToken);

        return Ok(result);
    }

    /// <summary>
    /// Streams the binary content of a stored file back to the caller.
    /// </summary>
    /// <remarks>
    /// Authorization is enforced at the application layer: the handler loads the aggregate and
    /// verifies that the requested <paramref name="file"/> + <paramref name="target"/> pair exists
    /// before delegating to <c>IFileStorage.DownloadAsync</c>. Passing an arbitrary cloud path
    /// directly is intentionally not supported.
    ///
    /// The <c>Content-Disposition</c> header is set to <c>inline</c> when <paramref name="viewInBrowser"/>
    /// is <see langword="true"/> (renders in the browser tab) or <c>attachment</c> otherwise (triggers
    /// a file-save dialog). The filename used is <c>FileDetail.FullName</c> from the aggregate.
    /// </remarks>
    /// <param name="id">The <see cref="Guid"/> of the owning <c>FileStorageAggregate</c>.</param>
    /// <param name="file">The full name (name + extension) of the file to download, as stored in <c>FileDetail.FullName</c>.</param>
    /// <param name="target">The logical storage target / folder the file was uploaded to.</param>
    /// <param name="viewInBrowser">
    /// When <see langword="true"/>, sets <c>Content-Disposition: inline</c> so the browser attempts
    /// to render the file. When <see langword="false"/>, sets <c>Content-Disposition: attachment</c>
    /// to force a download.
    /// </param>
    /// <param name="cancellationToken">Propagates cancellation from the HTTP pipeline.</param>
    /// <returns>The raw file stream with the MIME type resolved from <c>FileDetail.Mime.MimeType</c>.</returns>
    /// <response code="200">File stream returned successfully.</response>
    /// <response code="400">The <paramref name="file"/> / <paramref name="target"/> pair was not found on the aggregate.</response>
    /// <response code="401">Missing or invalid bearer token.</response>
    /// <response code="404">No aggregate exists for the supplied <paramref name="id"/>.</response>
    [HttpGet("[action]/{id}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Download(Guid id, [FromQuery] string file, [FromQuery] string target, [FromQuery] bool viewInBrowser, CancellationToken cancellationToken)
    {
        var query = new DownloadQuery(id, file, target);

        var result = await mediator.Send(query, cancellationToken);

        var contentDisposition = viewInBrowser ? "inline" : "attachment";
        Response.Headers.Append("Content-Disposition", $"{contentDisposition}; filename=\"{result.File.FullName}\"");

        return File(result.Stream, result.File.Mime.MimeType);
    }

    /// <summary>
    /// Uploads a file and associates it with an existing or new file-storage aggregate.
    /// </summary>
    /// <remarks>
    /// The request must be sent as <c>multipart/form-data</c>. The form fields defined in
    /// <see cref="FileUploadDto"/> (<c>Id</c>, <c>Target</c>, <c>Renowned</c>) must appear
    /// <strong>before</strong> the file part in the multipart body, because the handler reads
    /// them off the stream in order without buffering.
    ///
    /// <c>[DisableFormValueModelBinding]</c> is applied to prevent ASP.NET Core from buffering
    /// the request body. Kestrel's <c>MaxRequestBodySize</c> is set to <see langword="null"/> and
    /// <c>FormOptions.MultipartBodyLengthLimit</c> to <see cref="long.MaxValue"/>, so there is no
    /// enforced size cap at the framework level. Apply quota checks at the infrastructure or
    /// cloud-provider layer.
    ///
    /// On success the file is persisted via <c>IFileStorage</c> and a <c>FileStorageCreated</c>
    /// domain event is published through <c>IPubSub</c>.
    /// </remarks>
    /// <param name="data">
    /// Metadata bound from the form fields:
    /// <list type="bullet">
    ///   <item><description><c>Id</c> — the target <c>FileStorageAggregate</c> identifier (must be a non-empty <see cref="Guid"/>).</description></item>
    ///   <item><description><c>Target</c> — the logical folder / container the file is stored under.</description></item>
    ///   <item><description><c>Renowned</c> — when <see langword="true"/>, marks the file for public/featured exposure in the domain.</description></item>
    /// </list>
    /// </param>
    /// <param name="file">The uploaded file part. Must be non-null and have a length greater than zero.</param>
    /// <param name="cancellationToken">Propagates cancellation from the HTTP pipeline.</param>
    /// <returns><see cref="OkResult"/> (HTTP 200) on success.</returns>
    /// <response code="200">File uploaded and aggregate updated successfully.</response>
    /// <response code="400">No file was included in the request, or validation of <see cref="CreateFileStorageCommand"/> failed.</response>
    /// <response code="401">Missing or invalid bearer token.</response>
    [HttpPost("[action]")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> Upload([FromForm] FileUploadDto data, IFormFile file, CancellationToken cancellationToken)
    {
        if (file == null || file.Length == 0)
        {
            return BadRequest("No file uploaded.");
        }

        var command = new CreateFileStorageCommand(data.Id, file.OpenReadStream(), file.FileName, data.Target, data.Renowned);

        await mediator.Send(command, cancellationToken);

        return Ok();
    }
}